### ISSUE TITLE
How can I get the audiofiles used to get the train, test  and dev mdtm files.

### ISSUE THREAD

**Issue by MohanKrishna-RC** [pyannote/pyannote-db-etape#1]
How can I get the audiofiles used to get the train, test  and dev mdtm files.

**Comment by hbredin** [comment]
It is [distributed by ELRA](http://catalog.elra.info/en-us/repository/browse/etape-evaluation-package/edd16080a9d611e7a093ac9e1701ca02450fc333ba7e4eaaa1963e3fda526546/).

Note that it is not free: this is why I recently switched pyannote.audio tutorial to using the AMI corpus.
